version: '3.8'
services:
  backend:
    image: maryamhamood/mern-ecommerce:latest
    ports:
      - "4000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/mernapp
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: jenkins-mongo
    ports:
      - "27018:27017"
    volumes:
      - jenkins-mongo-data:/data/db

volumes:
  jenkins-mongo-data:
